site_name: Starmadepy Docs
repo_url: https://github.com/DerekRies/starmadepy
site_description: An easy to use python library for starmade game data. Can load starmade template files and allow you to edit them programmatically.
theme: readthedocs
pages:
 - [index.md, Home]
 - [getting-started.md, Getting Started]
 - [api.md, API]
 - [contributing.md, Contributing]
 - [projects.md, Projects Using Starmadepy]
 - [about.md, About]